---
- name: Run Nginx container
  hosts: servers
  gather_facts: false
  become: true
  vars_prompt:
    - name: docker_username
      prompt: "Please enter docker loginusername"
    - name: docker_password
      prompt: "Please enter docker login password"
  tasks:
    - name: Update repos
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - curl
          - docker.io
          - net-tools

    - name: Log into DockerHub
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
      become: true
      become_user: root

    - name: Allow incoming connection on 443
      ufw:
        rule: allow
        port: 443
        proto: tcp

    - name: Run Nginx Container
      docker_container:
        name: nginx-example-docker
        image: nginx:latest
        state: started
        ports:
          - "443:443"